
FROM node:19-alpine as base

ARG app_path=/app

RUN mkdir -p $app_path

WORKDIR $app_path

# Dockerfile to build and run the Node.js application

# # Use the most recent LTS version of Node.js as the base image
# FROM node:lts-alpine

# # Set the working directory to /app
# WORKDIR /app

# Copy package.json and package-lock.json to the Docker image
COPY package.json yarn.lock $app_path/

# Install dependencies
#RUN apk --no-cache add yarn && yarn install
RUN apk --no-cache add yarn && yarn install --production --frozen-lockfile

# Copy the application code to the Docker image
COPY . $app_path

FROM base as development 
# Set the environment to development
ENV NODE_ENV=development

# Expose port 3000 to the host
EXPOSE 3000

# Start the Node.js application from the /app/build directory
CMD [ "yarn", "start:dev" ]


FROM base as production

RUN yarn build

COPY .env $app_path/build/

# Set the environment to production
ENV NODE_ENV=production

# Expose port 3000 to the host
EXPOSE 3000

# CMD npm run star

CMD ["yarn", "start"]
# Start the Node.js application from the /app/build directory
#CMD ["node", "build/index.js"]
