version: '3.9'
services:
  poc_nodejs:
    env_file: .env
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: dockerfile.yml
      target: development
    volumes:
      - .:/app
