
FROM node:19-alpine as base

ARG app_path=/app

RUN mkdir -p $app_path

WORKDIR $app_path

# Copy the application code to the Docker image
COPY . $app_path

FROM base as development 
ENV NODE_ENV=development
EXPOSE 3000
CMD [ "yarn", "start:dev" ]


FROM base as production
COPY package.json yarn.lock $app_path/
RUN apk --no-cache add yarn && yarn install --production --frozen-lockfile
RUN yarn build
COPY .env $app_path/build/
ENV NODE_ENV=production
EXPOSE 3000
CMD ["yarn", "start"]
